### ISSUE TITLE
version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by longfangithub** [wexeee/fsl_mrs#1]
I test fsl_mrs on ubuntu16.04, the following issues arise:
OSError: Unable to load '/usr/local/anaconda3/lib/python3.7/site-packages/hlsvdpro/bin/libhlsvdpro.so'. The OS reports: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/anaconda3/lib/python3.7/site-packages/hlsvdpro/bin/libhlsvdpro.so).

I googled this and the solution is to upgrade the OS. But there are some problems to update my OS...are there any other solution?

**Comment by wexeee** [comment]
Hi @longfangithub, Thanks for the bug report. This arises from the packaged hlsvdpro library. We obviously compiled on a newer linux distro and I see (also googling) that this is now a common issue. I agree that upgrading is not a great solution.

I have two suggestions:
1) Quick & dirty. Uninstall hlsvdpro `conda remove hlsvdpro` and install a pypi version `pip install hlsvdpro==1.0.1`. Mixing conda and pip is not a good idea in general but it might get you a working version.
2) Brian Soher has just released a pure python version of the package. https://pypi.org/project/hlsvdpropy/ In the next bug fix version of fsl-mrs (1.0.3) I will switch to this, and that should solve these sorts of OS dependent issues. I hope to have that out in the next couple of days.

**Comment by wexeee** [comment]
Hi @longfangithub. I've put a new version  of FSL-MRS (V1.0.3) up on the fsl conda channel and on git. It should now be linked to a pure python version of hlsvdpro. Could you let me know if that solves the above issue?

**Comment by longfangithub** [comment]
It is working. Thanks!



---Original---

**Comment by wexeee** [comment]
@longfangithub Sorry I didn't notice your reply. Glad it's working. I'll close this issue now but let me know if you need any other help with the toolbox.
