### ISSUE TITLE
Windows installation aux directory name

### ISSUE THREAD

**Issue by JoeZiminski** [wexeee/fsl_mrs#3]
Dear FSL MRS developers,

Thanks for the provision of this toolbox, I'm really looking forward to trying it out. I am using Windows primarily (Windows 10, 64-bit) and am getting the error 'fatal: cannot create directory at 'fsl_mrs/aux': Invalid argument' when trying to clone the repo.

This seems to be related to this [1] very strange anomaly of windows that 'aux' folder name is reserved. I just confirmed this, I am unable to make a directory called aux; this is very strange but I guess it means fsl_mrs will not work on Windows containing the directory 'aux'.

For now I will switch to Linux, and I see fsl_mrs is not tested on Windows; I am happy to help test deployment to Windows if it would be useful.

Best,
Joe

[1] https://stackoverflow.com/questions/36225708/cannot-create-a-directory-named-aux-or-starting-by-aux-on-windows-8-1

**Comment by wexeee** [comment]
Hi @JoeZiminski,

Thanks for the report. Something I wasn't aware of, this should be an easy fix. I'll change the name of that folder in the upcoming release.

For the meantime do try try running on linux or WSL(2) and let me know if you have any issues.
