### ISSUE TITLE
MRSI fitting : no absolute quantification will be performed

### ISSUE THREAD

**Issue by inokentiyTTT** [wexeee/fsl_mrs#6]
Hi Will! Thank you very much for possibility of using fsl_mrs. Actually now I am exploring  of fsl_mrs and I got problem with running test example   fsl_mrs MRSI Fitting when I run second cell I see err:
            
            

>   %sx fsl_mrsi --data example_data/example_mrsi/mrsi.nii.gz \
>              --basis example_data/example_mrsi/3T_slaser_32vespa_1250.BASIS \
>              --output MRSI/example_mrsi_fit \
>              --mask example_data/example_mrsi/mask.nii.gz \
>              --h2o example_data/example_mrsi/wref.nii.gz \
>              --tissue_frac MRSI/mrsi_seg_wm.nii.gz MRSI/mrsi_seg_gm.nii.gz MRSI/mrsi_seg_csf.nii.gz \
>              --add_MM \
>              --baseline_order 2 \
>              --combine PCho GPC --combine Cr PCr --combine NAA NAAG --combine Glu Gln --combine Glc Tau \
>              --ignore Gly HG \
>              --overwrite

['Found duplicate basis name "Gly", renaming to "Gly_1".',
 '/home/iurii/anaconda3/envs/fsl_mrs/bin/fsl_mrsi:440: UserWarning:',
 '',
 'H2O file provided but could not determine TE: no absolute quantification will be performed.', '',
 '/home/iurii/anaconda3/envs/fsl_mrs/bin/fsl_mrsi:444: UserWarning:','',
 'H2O file provided but could not determine TR: no absolute quantification will be performed.','']

Could you please advise me with this problem?\

Regards,
Iurii

**Comment by wexeee** [comment]
Hi Iurii,

Thanks for this bug report. I think I encountered this recently and thought I had fixed it, but I neglected to check the example data. Could you try updating to the most recent version (1.1.4) and try again? I was uploaded to the conda channel yesterday. I'll also look into this shortly.

Will

**Comment by inokentiyTTT** [comment]
Hi Will,
Thank you very much  for your respond! I have  update it to  most recent version (1.1.4) but the problem still exist. Also I try it with wsl on Windows 10 but there I have even not able to use segmentation:

Regards,
Iurii

**Comment by inokentiyTTT** [comment]
Hi Will,
Thank you very much  for your respond! I have  update it to  most recent version (1.1.4) but the problem still exist. Also I try it with wsl on Windows 10 but there I have even not able to use segmentation:
['',
 'Part of FSL (build 508)',
 'applywarp ',
 'Copyright(c) 2001, University of Oxford (Jesper Andersson)',
 '',
 'Usage: ',
 'applywarp -i invol -o outvol -r refvol -w warpvol',
 'applywarp -i invol -o outvol -r refvol -w coefvol',
 '',
 '',
 'Compulsory arguments (You MUST set one or more of):',
 '\t-i,--in\tfilename of input image (to be warped)',
 '\t-r,--ref\tfilename for reference image',
 '\t-o,--out\tfilename for output (warped) image',
 '',
 'Optional arguments (You may optionally specify one or more of):',
 '\t-w,--warp\tfilename for warp/coefficient (volume)',
 "\t--abs\t\ttreat warp field as absolute: x' = w(x)",
 "\t--rel\t\ttreat warp field as relative: x' = x + w(x)",
 '\t-d,--datatype\tForce output data type [char short int float double].',
 '\t-s,--super\tintermediary supersampling of output, default is off',
 "\t--superlevel\tlevel of intermediary supersampling, a for 'automatic' or integer level. Default = 2",
 '\t--premat\tfilename for pre-transform (affine matrix)',
 '\t--postmat\tfilename for post-transform (affine matrix)',
 '\t-m,--mask\tfilename for mask image (in reference space)',
 '\t--interp\tinterpolation method {nn,trilinear,sinc,spline}',
 '\t--paddingsize\tExtrapolates outside original volume by n voxels',
 '\t-v,--verbose\tswitch on diagnostic messages',
 '\t-h,--help\tdisplay this message',
 '',
 '',
 '',
 'Exception in thread Thread-2:',
 'Traceback (most recent call last):',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/threading.py", line 932, in _bootstrap_inner',
 '    self.run()',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/threading.py", line 870, in run',
 '    self._target(*self._args, **self._kwargs)',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/site-packages/fsl/utils/run.py", line 116, in realForward',
 "    else:                o.write(line.decode('utf-8'))",
 "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 1: invalid continuation byte",
 'Traceback (most recent call last):',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/bin/mrsi_segment", line 76, in <module>',
 '    main()',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/bin/mrsi_segment", line 65, in main',
 "    applywarp_func(op.join(anat, 'T1_fast_pve_0.nii.gz'),",
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/bin/mrsi_segment", line 56, in applywarp_func',
 '    applywarp(i,',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/site-packages/fsl/wrappers/wrapperutils.py", line 1094, in wrapper',
 '    result = fot(*args, **kwargs)',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/site-packages/fsl/wrappers/wrapperutils.py", line 756, in __call__',
 '    result = func(*args, **kwargs)',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/site-packages/fsl/wrappers/wrapperutils.py", line 1136, in wrapper',
 '    return fot(*args, **kwargs)',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/site-packages/fsl/wrappers/wrapperutils.py", line 756, in __call__',
 '    result = func(*args, **kwargs)',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/site-packages/fsl/wrappers/wrapperutils.py", line 197, in wrapper',
 '    return runner(cmd,',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/site-packages/fsl/utils/run.py", line 390, in runfsl',
 '    return run(*args, **kwargs)',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/site-packages/fsl/utils/run.py", line 225, in run',
 '    stdout, stderr, exitcode = _realrun(',
 '  File "/home/iurii/anaconda3/envs/fsl_mrs/lib/python3.8/site-packages/fsl/utils/run.py", line 343, in _realrun',
 "    stderr   = stderr.decode('utf-8')",
 "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 1204: invalid continuation byte"]
Regards,
Iurii

**Comment by wexeee** [comment]
Hi @inokentiyTTT Thanks for confirming this. I've reopened the issue so it says on my radar. I'll take a look at this soon.

Will

**Comment by wexeee** [comment]
Hi @inokentiyTTT I believe everything should be fixed in version 1.1.5 which has now been released. Thanks again for the bug report.
